version: "3.7"

services:
  web:
    build: .
    entrypoint: ["/srv/migrate.sh"]
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/srv
    ports:
      - "3000:3000"
